name: Sphinx

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: pip3 install sphinx-rtd-theme
    
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
